<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>User account</title>
    <link rel="stylesheet"  href="mystyle.css"/>
  </head>

  <body>
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <header>
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <img class="mx-auto h-10 w-auto" src="/web/images/todolis_logo.png" alt="ToDoListLogo">
            <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Welcome, <?php echo $_SESSION['user']; ?> </h2>
            <a href="?logout">Log out</a> 
        </div>
    </header> 
  
  </div>
  </body>


</html>