<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Welcome to ToDoList</title>
    <link rel="stylesheet"  href="mystyle.css"/>
  </head>
  <body class="bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
    <div class="bg-white rounded-lg shadow-md flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">To Do List Manager</h2>
        </div>
        <br><br>

        <div>
            <a href="RegisterView.phtml" class="flex w-full justify-center rounded-md bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 px-3 py-1.5 text-sm font-semibold leading-6 text-black shadow-sm group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400">Register</a>
            <br><br>
            <a href="LoginView.phtml" class="flex w-full justify-center rounded-md bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 px-3 py-1.5 text-sm font-semibold leading-6 text-black shadow-sm group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400">Log in</a>
        </div>


    </div>

</html>