<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Welcome to ToDoList</title>
    <link rel="stylesheet"  href="mystyle.css"/>
  </head>
  <body class="bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
    <div class="bg-white rounded-lg shadow-md flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
          
            <img class="mx-auto h-10 w-auto" src="images/todolis_logo.png" alt="ToDoListLogo">
            <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">To Do List Manager</h2>
        </div>

        <div>
            <a href="RegisterView.phtml" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Register</a>
            <br><br>
            <a href="LoginView.phtml" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Login</a>
        </div>


    </div>

</html>