<!DOCTYPE html>
<html>
<head>
    <title>Edit Task</title>
</head>
<body>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <h1>Edit Task</h1>
   
    <?php 
   
            $taskDetails= $this->taskDetails;
       
            if (isset($taskDetails) && is_array($taskDetails)): 
             
    
    ?>
    
    <form method="POST" action="saveTask">
        <div class="grid gap-4 mb-4 sm:grid-cols-2">
        
        <input type="hidden" name="task_id" value="<?php  echo $taskDetails['task_id']; ?>">
        <div>
            <label for="task_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Name:</label>
            <input type="text" name="task_name" value="<?php  echo $taskDetails['task_name']; ?>">
        </div>
        <div>
            <label for="task_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Description:</label>
            <input type="text" name="task_description" value="<?php echo $taskDetails['task_description']; ?>">
        </div>
        <div>
            <label for="start_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Start Date:</label>
            <input type="date" name="start_date" value="<?php echo $taskDetails['start_date']; ?>">
            </div>
        <div>
            <label for="finish_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Finish Date:</label>
            <input type="date" name="finish_date" value="<?php echo $taskDetails['finish_date']; ?>">
        </div>
        <div>
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Status:</label>
            <select name="status" id="status" >
                <option value="Not_Started" <?php echo ($taskDetails['status'] === 'Not_Started') ? 'selected' : ''; ?>>Not Started</option>
                <option value="In_Progress" <?php echo ($taskDetails['status'] === 'In_Progress') ? 'selected' : ''; ?>>In Progress</option>
                <option value="Completed" <?php echo ($taskDetails['status'] === 'Completed') ? 'selected' : ''; ?>>Completed</option>
                <option value="Cancelled" <?php echo ($taskDetails['status'] === 'Cancelled') ? 'selected' : ''; ?>>Cancelled</option>
            </select>
        </div>
        <div>       
            <label for="created_by" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Created By:</label>
            <input type="text" name="created_by" value="<?php echo $taskDetails['created_by']; ?>">
        </div>

        <form method="POST" action="saveTask">
                        <input type="hidden" name="task_id" value="<?php echo $taskDetails['task_id']; ?>">
                        <button type="submit" class="text-white inline-flex items-center text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Save</button>
                    </form>
        
    
    </form>
            </div>
    <?php   // endforeach; 
            endif;  ?>
            </div>
</body>

</html>