<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="x-ua-compatible" content="ie=edge"/>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>To Do List</title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.css"  rel="stylesheet" />
        <link rel="stylesheet"  href="mystyle.css"/>
    </head>
    <body>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <header>
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <img class="mx-auto h-10 w-auto" src="/web/images/todolis_logo.png" alt="ToDoListLogo">
           <!-- <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Welcome, <?php echo $_SESSION['user']; ?> </h2>-->
            <a href="?logout">Log out</a> 
        </div>
    </header> 


    <h1>Create Task</h1>

    <form method="POST" action="createTask">
        <label for="task_name">Task Name:</label>
        <input type="text" name="task_name" id="task_name" required>

        <label for="task_description">Task Description:</label>
        <input type="text" name="task_description" id="task_description" required>

        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date" id="start_date" required>

        <label for="finish_date">Finish Date:</label>
        <input type="date" name="finish_date" id="finish_date" required>

        <label for="status">Status:</label>
        <select name="status" id="status" >
            <option value="Not Started">Not Started</option>
            <option value="In Progress">In Progress</option>
            <option value="Completed">Completed</option>
            <option value="Cancelled">Cancelled</option>
        </select>

        <label for="created_by">Created By:</label>
        <input type="text" name="created_by" id="created_by" required>
        
        <button type="submit">Create Task</button>
    </form>

        <h1>Task List</h1>
        
        <?php  if (isset($_SESSION['success_message'])): ?>
            <div class="success-message">
                <?php echo $_SESSION['success_message']; ?>
            </div>
        <?php endif; ?>
    
        <h2>All Tasks </h2>
        
        <table >
            <thead>
                <tr>
                    <th>Task Name</th>
                    <th>Task Description</th>
                    <th>Start Date</th>
                    <th>Finish Date</th>
                    <th>Status</th>
                    <th>Created By</th>
                </tr>
            </thead>
            <tbody>
            
            <?php
            
            $taskDetails= $this->taskDetails;
            //var_dump($taskDetails);
            if (isset($taskDetails) && is_array($taskDetails)): 
                foreach ($taskDetails as $task): 
        ?>  
            <tr>
            
                <td><?php echo $task['task_name']; ?></td>
                <td><?php echo $task['task_description']; ?></td>
                <td><?php echo $task['start_date']; ?></td>
                <td><?php echo $task['finish_date']; ?></td>
                <td><?php echo $task['status']; ?></td>
                <td><?php echo $task['created_by']; ?></td>
                <td><!-- Acciones --></td>
                <td>
                <td>
                <form method="POST" action="deleteTask">
                        <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                        <button type="submit">Delete</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="editTask">
                        <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                        <button type="submit">Edit</button>
                    </form>
                </td>
            
            </tr>
            <?php    endforeach; 
            endif;  ?>
                        </td>
                    </tr>
                
            </tbody>
        </table>
    <!-- Ventana modal de edición -->
    <div class="edit-modal" style="display: none;">
        <form method="POST" action="editTask">
            
            <input type="hidden" name="task_id" id="edit_task_id">
            <label for="edit_task_name">Task Name:</label>
            <input type="text" name="edit_task_name">
            <label for="edit_task_description">Task Description:</label>
            <input type="text" name="edit_task_description">
            <label for="edit_start_date">Start Date:</label>
            <input type="date" name="edit_start_date">
            <label for="edit_finish_date">Finish Date:</label>
            <input type="date" name="edit_finish_date">
            <label for="edit_status">Status:</label>
                <select name="edit_status" id="edit_status">
                    <option value="Not Started">Not Started</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Completed">Completed</option>
                    <option value="Cancelled">Cancelled</option>
                </select>
            <label for="edit_created_by">Created by:</label>
            <input type="text" name="edit_created_by">
           
            <button type="submit" name="save" value="save">Save</button>
        </form>
    </div>

        <!-- Create modal -->
    <div id="createProductModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <!-- Modal header -->
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Add Task</h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-target="createProductModal" data-modal-toggle="createProductModal">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <form method="POST" action="createTask">
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    <div>
                        <label for="task_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Name</label>
                        <input type="text" name="task_name" id="task_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type task name" required="">
                    </div>
                    <div>
                        <label for="task_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Description</label>
                        <input type="text" name="task_description" id="task_description" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Task Description" required="">
                    </div>
                    <div>
                        <label for="start_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Start Date</label>
                        <input type="date" name="start_date" id="start_date" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Start Date" required="">
                    </div>
                    <div>
                        <label for="finish_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Finish Date</label>
                        <input type="date" name="finish_date" id="finish_date" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Finish Date" required="">
                    </div>
                    <div><label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Status</label>
                    <select name="status" id="status" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                        <option selected="">Select status</option>
                        <option value="Not Started">Not Started</option>
                        <option value="Completed">Completed</option>
                        <option value="Cancelled">Cancelled</option>
                        </select>
                        </div>
                        <div>
                        <label for="created_by" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Created By</label>
                        <input type="text" name="created_by" id="created_by" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Created By" required="">
                    </div>
                    
                        </div>
                        <button type="submit" class="text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                            <svg class="mr-1 -ml-1 w-6 h-6" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
                            </svg>
                            Create Task
                        </button>
            </form>
        </div>
    </div>
    </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
    </body>
    </html>