<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="x-ua-compatible" content="ie=edge"/>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>To Do List</title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.css"  rel="stylesheet" />
    </head>
    
    <body>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    

    <section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5 antialiased">

    <h1>Create Task</h1>

    <form method="POST" action="createTask">
        <label for="task_name">Task Name:</label>
        <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    <div>
                        <label for="task_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Name</label>
                        <input type="text" name="task_name" id="task_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type task name" required="">
                    </div>
                    <div>
                        <label for="task_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Task Description</label>
                        <input type="text" name="task_description" id="task_description" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Task Description" required="">
                    </div>
                    <div>
                        <label for="start_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Start Date</label>
                        <input type="date" name="start_date" id="start_date" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Start Date" required="">
                    </div>
                    <div>
                        <label for="finish_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Finish Date</label>
                        <input type="date" name="finish_date" id="finish_date" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Finish Date" required="">
                    </div>
                    <div>
                        <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Status</label>
                        <select name="status" id="status" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                        <option selected="">Select status</option>
                        <option value="Not Started">Not Started</option>
                        <option value="Completed">Completed</option>
                        <option value="Cancelled">Cancelled</option>
                        </select>
                        </div>
                        <div>
                        <label for="created_by" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Created By</label>
                        <input type="text" name="created_by" id="created_by" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Created By" required="">
                    </div>
                    <button type="submit" class="text-white inline-flex items-center text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
                        <svg class="mr-1 -ml-1 w-6 h-6" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
                        </svg>
                        Add Task
                    </button>
    </form>

        <h1>Task List</h1>
        
        <?php  if (isset($_SESSION['success_message'])): ?>
            <div class="success-message">
                <?php echo $_SESSION['success_message']; ?>
            </div>
        <?php endif; ?>
    
        <h2>All Tasks </h2>
        
        <table >
            <thead>
                <tr>
                    <th>Task Name</th>
                    <th>Task Description</th>
                    <th>Start Date</th>
                    <th>Finish Date</th>
                    <th>Status</th>
                    <th>Created By</th>
                </tr>
            </thead>
            <tbody>
            
            <?php
            
            $taskDetails= $this->taskDetails;
            //var_dump($taskDetails);
            if (isset($taskDetails) && is_array($taskDetails)): 
                foreach ($taskDetails as $task): 
        ?>  
            <tr>
            
                <td><?php echo $task['task_name']; ?></td>
                <td><?php echo $task['task_description']; ?></td>
                <td><?php echo $task['start_date']; ?></td>
                <td><?php echo $task['finish_date']; ?></td>
                <td><?php echo $task['status']; ?></td>
                <td><?php echo $task['created_by']; ?></td>
                <td><!-- Acciones --></td>
                <td>
                <td>
                <form method="GET" action="deleteTask">
                        <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                        <button type="submit">Delete</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="emptyEdit">
                        <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                        <button type="submit">Edit</button>
                    </form>
                </td>
            
            </tr>
            <?php    endforeach; 
            endif;  ?>
                        </td>
                    </tr>
                
            </tbody>
        </table>

        </section>
    

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
    </body>
    </html>