
<!DOCTYPE html>
<html>
<head>
    <title>To-Do-List</title>
</head>
<body>
<h1>Create Task</h1>

<form method="POST" action="createTask">
    <label for="task_name">Task Name:</label>
    <input type="text" name="task_name" id="task_name" required>

    <label for="task_description">Task Description:</label>
    <input type="text" name="task_description" id="task_description" required>

    <label for="start_date">Start Date:</label>
    <input type="date" name="start_date" id="start_date" required>

    <label for="finish_date">Finish Date:</label>
    <input type="date" name="finish_date" id="finish_date" required>

    <label for="status">Status:</label>
    <select name="status" id="status" >
        <option value="Not Started">Not Started</option>
        <option value="In Progress">In Progress</option>
        <option value="Completed">Completed</option>
        <option value="Cancelled">Cancelled</option>
    </select>

    <label for="created_by">Created By:</label>
    <input type="text" name="created_by" id="created_by" required>
    
    <button type="submit">Create Task</button>
</form>

    <h1>Task List</h1>
    
    <?php  if (isset($_GET['success_message'])): ?>
        <div class="success-message">
            <?php echo $_GET['success_message']; ?>
        </div>
    <?php endif; ?>
   
    <h2>All Tasks </h2>
       
    <table >
        <thead>
            <tr>
                <th>Task Name</th>
                <th>Task Description</th>
                <th>Start Date</th>
                <th>Finish Date</th>
                <th>Status</th>
                <th>Created By</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        
        <?php
            if (isset($_SESSION['taskDetails'])) {
            $taskDetails = $_SESSION['taskDetails'];
            foreach ($taskDetails as $task): 
    ?>  
                <tr>
                    
                    <td><?php echo $task['task_name']; ?></td>
                    <td><?php echo $task['task_description']; ?></td>
                    <td><?php echo $task['start_date']; ?></td>
                    <td><?php echo $task['finish_date']; ?></td>
                    <td><?php echo $task['status']; ?></td>
                    <td><?php echo $task['created_by']; ?></td>
                    <td>
                        <?php endforeach;}?> 

                        <!--editTask-->

                        <!-- <a href="editTask/<?php echo $task['task_id']; ?>">Edit</a>
                        
                        <--deleteTask-->
                        <!-- <form method="POST" action="deleteTask">
                            <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                            <button type="submit">Delete</button>
                       </form> -->
                    </td>
                </tr>
            
        </tbody>
    </table>

    

</body>
</html>