<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="bg-indigo-600">
    <!-- Header Section -->
    <header class="bg-indigo-600">
        <div class="container mx-auto flex items-center justify-between">
            <a href="/Sprint3/ToDoList/web/index" class="text-white text-2xl font-semibold">LEIPA</a>
			<br>
            
        </div>
    </header>

    <!-- Main Content Section -->
    <div class="container mx-auto mt-8 p-4">
        <?= $this->content() ?>
    </div>
</body>
</html>
